import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToolBar from "@/components/Toolbar";
import Container from "@/components/Container/Container";
import Lenis from "@/components/SmoothScroll";
import { ToolBarBackClickProvider } from "@/conext/ScaleContext";
import AppLayout from "./layout/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JuiceBox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const onBackClick = () => {};
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
